language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - Gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-master.gemfile
before_script:
  - gem update --system
matrix:
  exclude:
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.4.5
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
