language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - 2.4.0
  - 2.5.0
gemfile:
  - Gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-master.gemfile
before_script:
  - gem update --system
matrix:
  exclude:
    - gemfile: Gemfile
      rvm: 2.1.8
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.1.8
    - gemfile: gemfiles/rails-5.0.gemfile
      rvm: 2.1.8
    - gemfile: gemfiles/rails-4.2.gemfile
      rvm: 2.4.0
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
