language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile
  - gemfiles/rails-5.0.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails-5.0.gemfile
      rvm: 2.1.8
